### PR TITLE
Adds Flutter Config

### PR DESCRIPTION
**Pull request by StrangeNoob**
Adds .env in the Flutter Part.
Adds .env.example for refernces.
@aquibbaig Can you check if this works for iOS or not?

### CODE REVIEW

**Comment by aquibbaig** [comment]
Why does this PR introduce 98 file changes? You might want to clear that up

**Comment by StrangeNoob** [comment]
@aquibbaig I think I have updated the flutter SDK. I think it might have caused this

**Comment by aquibbaig** [comment]
@StrangeNoob Please revert back to the base branch and commit again. Updating flutter SDK causes things to break in the `ios` end. Hence I have kept it that way.

**Comment by StrangeNoob** [comment]
@aquibbaig Okay. I will close this pr and send it change.

**Pull request closed without merging**
